Decanat/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Decanat.Filters;

namespace Decanat.Controllers
{
    
    public class DefaultController : Controller
    {
        //
        // GET: /Default1/

        public ActionResult Index()
        {
            #region Опрос Cookies
            //var cookies = Request.Cookies["NCGTI_USER_NAME"];
            //string TargetRole = "Деканат";
            //string AuthAddress = "http://portal.ncgti.ru";
            //string ip = Request.UserHostAddress;

            //if ((ip.Contains("192.168")) || (ip.Contains("::"))) // ::1
            //    AuthAddress = "http://portal.ncgti.lan";

            //if (cookies != null)
            //{
            //    string UserName = cookies.Value.ToString();
            //    var context = new JournalEntities();
            //    var Roles = context.GetUserRoles(UserName).ToArray();
            //    if (Roles.Any(item => item.Role == TargetRole))
            //        ViewBag.AuthMessage = UserName + " : " + TargetRole; 
            //    else
            //        Response.Redirect(AuthAddress);
            //}
            //else
            //{
            //    ViewBag.AuthMessage = "нет пользователя";
            //    Response.Redirect(AuthAddress);
            //}
            #endregion // Опрос Cookies

            return View();
        }

        [HttpPost]
        public JsonResult GetGroupCollection()
        {

            #region Получение данных

            var context = new JournalEntities();
            var dbResult = context.GetGroupCollection(null, String.Empty, null, null, null, null, String.Empty).ToList();

            var groups = (from gr in dbResult select new
            {
                gr.Код,
                gr.Код_Факультета,
                gr.ФакСокращение,
                gr.Курс,
                gr.Название,
                gr.Учебный_План,
                gr.ФормаОбученияСокр,
                gr.ОКСО
            });

            //int a = 1;

            #endregion // Получение данных

            return Json(groups, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult GetVedomCollection(int pGrCode, String pPlanName)
        {

            #region Получение данных

            var context = new JournalEntities();

            var dbResult = context.GetVedomCollection(pGrCode, pPlanName);

            var vedoms = (from veditem in dbResult
                          select new
                          {
                              veditem.Дисциплина,
                              veditem.Описание, // тип  ведомости
                              veditem.Курс,
                              veditem.Семестр,
                              veditem.вед_Преподаватель,
                              veditem.вед_Код, // скрытый
                              veditem.ИмяФайла, // скытый
                              veditem.ТипВедомости,  // скрытый
                              veditem.ВидСессии, // скрытый
                              veditem.СеместрВыч, // Скрытыйы
                              veditem.IsCurrentAtt,
                              veditem.IsNeedReiting,
                              veditem.Закрыта
                          });

            // int a = 1;

            #endregion // Получение данных

            return Json(vedoms, JsonRequestBehavior.DenyGet);
        }


        public JsonResult AddNewVedom(int pGroupCode, string pPlanName, string pDiscipl, int pKurs, int pSem, int pSess, int pVedType)
        {
            var context = new JournalEntities();
            
            var message = "";

            try
            {
                var dbResult = context.AddNewVedom(pGroupCode, pPlanName, pDiscipl, pKurs, pSem, pSess, pVedType);
                message = "Success";
            }
            catch (Exception)
            {
                message = "Error";
            }

            return Json(message, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetStudCollection(int pGroupCode)
        {
            var context = new JournalEntities();

            var dbResult = context.GetStudentCollection(pGroupCode);

            var students = (from stud_item in dbResult select 
                                new {
                                    stud_item.Код,
                                    stud_item.ФИО,
                                    stud_item.Статус,
                                    stud_item.IsZadolzh
                                });

            int a = 0;

            return Json(students, JsonRequestBehavior.DenyGet);
        }

        public JsonResult GetStudentZadolzh(int pStudentId)
        {
            var context = new JournalEntities();

            var dbResult = context.GetStudentZadolzh(pStudentId);

            var zadolzh = (from item in dbResult
                            select
                                new
                                {
                                    item.Дисциплина,
                                    item.Курс,
                                    item.Семестр,
                                    item.СеместрВыч,
                                    item.Сессия,
                                    item.вед_Преподаватель,
                                    item.вед_Код,
                                    item.ТипВедомости,
                                    item.Описание,
                                    item.Итог,
                                    item.Итоговая_Оценка,
                                    item.id,
                                    item.ocenka,
                                    item.isclosed,
                                    item.Примечание
                                });

            int a = 0;

            return Json(zadolzh, JsonRequestBehavior.DenyGet);
        }

        public JsonResult SaveBegunOcenka(int pBegunId, int pOcenkaCode)
        {
            string res = "ok";

            var context = new JournalEntities();

            var dbres = context.UpdateBegunokById(pBegunId, pOcenkaCode);

            return Json(res, JsonRequestBehavior.DenyGet);
        }

        public JsonResult CreateBegunForGroup(int pGroupCode)
        {
            string res = "ok";

            var context = new JournalEntities();

            var dbres = context.CreateNewBegunForGroup(pGroupCode);

            return Json(res, JsonRequestBehavior.DenyGet);
        }

    }
}

Decanat/Controllers/VedomDocController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Http.Description;
using System.Web.Mvc;
using Decanat.Models;
using Microsoft.Ajax.Utilities;
using System.Web.Script.Serialization;

namespace Decanat.Controllers
{
	public class VedomDocController : Controller
	{
		private JournalEntities context = new JournalEntities();

		public ActionResult Index(int pVedCode)
		{
		    if (Session["UserName"] == null)
		    {
		        // Что-нибудь делаем для авторизации пользователя
                Session["UserName"] = "Undefined, host: " + Request.UserHostName + "address: " + Request.UserHostAddress;
		    }
		    else
		    {
		        
		    }

            //int pVedCode = 298154;

            var curVedDescription = new VedomDescription(pVedCode, false);

            // Определим преподавателя для ведомости
            //if (curVedDescription.VedType == "Зачет")
            //{
            //    if (curVedDescription.FIOLab == "-")
            //        ViewBag.Prepod = curVedDescription.FIOPrakt;
            //}
            //else 
            //{
            //    ViewBag.Prepod = curVedDescription.FIOLektor;
            //}

            return View(curVedDescription);
		}

        /// <summary>
        /// Контроллер, формирующий печатную форму определенного типа
        /// </summary>
        /// <param name="pVedCode">Код ведомости</param>
        /// <param name="pPrintType">0 - Печать заполненной ведомости, 1 - Печать пустого бланка ведомости, 2 - Печать бланка с просавленными допусками</param>
        /// <returns></returns>
        public ActionResult PrintVedom(int pVedCode, int pPrintType)
        {
            VedomDocument VedDescr = new VedomDocument(pVedCode, true);
            ViewBag.PrintType = pPrintType;
            return View(VedDescr);
        }

		[HttpGet]
		public JsonResult GetOcenkiForVedom(int pVedCode)
		{

			var dbResult = context.GetOcenkiCollectionForVedom(pVedCode, null);

			var ocenki = (from oc in dbResult select new
						  {
                              oc.оц_Код,
							  oc.вс_Код,
							  УчетВВед=oc.УчетВВед,
							  ФИО=oc.Фамилия + " " + oc.Имя + " " + oc.Отчество,
							  Зачетка=oc.Зачетка,
							  oc.РейтинговыйБалл,
							  oc.ДопускПоОплате,
                              oc.Итоговая_Оценка,
                              oc.Итог,
                              oc.Рейтинг_Оценка,
                              oc.ИнтИОц,
                              oc.ИнтИОцО,
                              oc.ИнтИтогО,
                              oc.МожетПравить
						  });

			return Json(ocenki, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetBegunkiForStudent(int pStudentId, int pVedCode)
		{
			var dbResult = context.GetBegunkiForStudent(pStudentId, pVedCode);

			var begunki = (from b in dbResult select new
			{
                	b.id,
	                b.id_ved,
	                b.id_stud,
	                b.date_create,
	                b.date_give,
	                b.date_expired,
	                b.date_lastupdate,
	                b.ocenka,
	                b.description,
	                b.user_last,
                    b.isclosed
			});

			return Json(begunki, JsonRequestBehavior.AllowGet);
		}

        [HttpPost]
        public JsonResult SaveAllOcenki(string OcenkiItems)
        {
            // Сообщение пользователю
            string ResMessage = "";
            int LocalRes = 0;

            try
            {
                List<ItemHelper> Ocenki = new JavaScriptSerializer().Deserialize<List<ItemHelper>>(OcenkiItems);
                                            
                int LocCurrentVedom = Convert.ToInt32(Ocenki[0].VedomCode);

                // Получаем список допустимых оценок для ведомости
                var TypesOfOcenki = context.GetOcenkiForVedom(LocCurrentVedom).ToArray();
                
                // Сохраняем оценки по одной
                int LocCurTypeOfOcenka,
                    LocOcenkaCode = -1,
                    LocUchet = 0;

                string LocUser = (Session["UserName"] != null) ? Session["UserName"].ToString() : "Undef";
                
                foreach (var helper in Ocenki)
                {
                    LocCurTypeOfOcenka = Convert.ToInt32(helper.OcenkaTypeCode);
                    int a = 0;
                    // Проверяем, чтобы оценка попала в нужный диапазон
                    if (TypesOfOcenki.Any(item => item.КодИАСУ == LocCurTypeOfOcenka))
                    {
                        if (helper.OcenkaCode == null)
                            LocOcenkaCode = -1;
                        else
                        {
                            LocOcenkaCode = Convert.ToInt32(helper.OcenkaCode);
                        }
                        if (helper.Uchet.ToUpper() == "TRUE")
                            LocUchet = 1;
                        else
                            LocUchet = 0;

                        // Только тогда сохраняем
                        LocalRes = context.SetOcenkaVedom(
                            LocCurrentVedom, 
                            Convert.ToInt32(helper.StudentCode), 
                            LocOcenkaCode, 
                            LocCurTypeOfOcenka,
                            LocUchet,
                            LocUser);

                        // Потом формируем заключение
                        if (LocalRes > 0)
                        {
                            ResMessage += "> Сохранено. ФИО: " + helper.StudentFIO
                                + "<br/>признак учета: <b>" + ((LocUchet == 1) ? "Учитывать" : "Не учитывать")
                                + "</b>, код оценки: <b>" + LocCurTypeOfOcenka.ToString() + "</b><br/>";
                        }
                    }
                    else
                    {
                        // Формируем сообщение об ошибке
                        ResMessage += "Не удалось сохранить: " + helper.StudentFIO + " - недопустимый код оценки: " + LocCurTypeOfOcenka.ToString() + "<br/>";
                    }
                    
                    
                }
            }
            catch
            {
                ResMessage = "Операция была завершена с ошибкой. Обратитесь к разработчикам";
            }

            if (ResMessage == "") ResMessage = "Ничего не сохранялось";

            return Json(ResMessage, JsonRequestBehavior.AllowGet);

        }

	    private class ItemHelper
	    {
            public string VedomCode {get; set; }
            public string StudentCode {get; set; }
            public string OcenkaCode {get; set; }
            public string OcenkaTypeCode {get; set; }
            public string Uchet { get; set; }
            public string StudentFIO { get; set; }  
        }

        [HttpPost]
	    public JsonResult CreateNewBegunok(int pVedCode, int pStudentId, DateTime pDateCreate, DateTime pDateGive, DateTime pDateExpired, int pOcenkaCode)
	    {
	        int LocalRes = -1;
	        string MessageRes = "";
            string LocDescr = "";
            string LocUser = "";

            if (Session["UserName"] != null)
            {
                // Что-нибудь делаем для авторизации пользователя
                LocUser = Session["UserName"].ToString();
            }
            else
            {
                LocUser = "Undefined, host: " + Request.UserHostName + "address: " + Request.UserHostAddress;
            }

            // Получаем список допустимых оценок для ведомости
            var TypesOfOcenki = context.GetOcenkiForVedom(pVedCode).ToArray();

            // Спрашиваем, попала ли оценка в требуемый диапазон
	        if (TypesOfOcenki.Any(item => item.КодИАСУ == pOcenkaCode))
	        {
                LocalRes = context.CreateNewBegunok(pVedCode, pStudentId, pDateCreate, pDateGive, pDateExpired, DateTime.Now,
                    pOcenkaCode, LocDescr, LocUser);
	        }
	        else
	        {
	            MessageRes = "Некорректный тип оценки. Бегунок не был создан";
	        }

	        if (LocalRes > 0)
	            MessageRes = "Создан бегунок";
	        else
	        {
	            MessageRes = "Бегунок не был создан";
	        }

	        return Json(MessageRes, JsonRequestBehavior.DenyGet);
	    }

        [HttpPost]
        public JsonResult EditBegunok(int pVedCode, int pBegunCode, int pStudentId, DateTime pDateCreate, DateTime pDateGive, DateTime pDateExpired, int pOcenkaCode)
        {
            //string str = Request.Url.AbsoluteUri;

            int LocalRes = -1;
            string MessageRes = "";
            string LocDescr = "";
            string LocUser = "";

            if (Session["UserName"] != null)
            {
                // Что-нибудь делаем для авторизации пользователя
                LocUser = Session["UserName"].ToString();  
            }
            else
            {
                LocUser = "Undefined, host: " + Request.UserHostName + "address: " + Request.UserHostAddress;
            }

            // Получаем список допустимых оценок для ведомости
            var TypesOfOcenki = context.GetOcenkiForVedom(pVedCode).ToArray();

            // Спрашиваем, попала ли оценка в требуемый диапазон
            if (TypesOfOcenki.Any(item => item.КодИАСУ == pOcenkaCode))
            {
                LocalRes = context.UpdateBegunok(pBegunCode, pStudentId, pVedCode, pDateCreate, pDateGive, pDateExpired, pOcenkaCode, LocUser);
            }
            else
            {
                MessageRes = "Некорректный тип оценки. Бегунок не был обновлен";
            }

            if (LocalRes > 1)
                MessageRes = "Бегунок обновлен";
            else
            {
                MessageRes = "Бегунок не был обновлен";
            }

            return Json(MessageRes, JsonRequestBehavior.DenyGet);
        }

        [HttpGet]

Decanat/Views/Default/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Аттестация";
}

@section scripts
{
    <script src="~/Scripts/Custom/Default.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            // Адрес метода создания ведомости
            sourceUrlVedomAdd = '@Url.Action("AddNewVedom", "", null, "http")';
            // Адрес метода редактирования ведомости
            sourceUrlVedomEdit = '@Url.Action("Index", "VedomDoc", new {pVedCode="param1"}, "http")';
            // Адрес метода печати заполненной ведомости ведомости
            sourceUrlVedomPrint = '@Url.Action("PrintVedom", "VedomDoc", new {pVedCode="param1", pPrintType="param2"}, "http")'; 
            // Адрес метода получения списка ведомостей
            sourceUrlVedomCollection = '@Url.Action("GetVedomCollection", "Default", new {pGrCode = "param1", pPlanName="param2"}, "http")'; 
            // Адрес метода получения списка студентов группы
            sourceUrlStudents = '@Url.Action("GetStudCollection", "Default",  new {pGroupCode="param1"}, "http")'; 
            // Адрес метода получения задолженностей для данного студента
            sourceUrlZadolzh = '@Url.Action("GetStudentZadolzh", "Default",  new {pStudentId="param1"}, "http")';   
            // Адрес метода сохранения оценки в бегунке
            sourceUrlSaveBegun = '@Url.Action("SaveBegunOcenka", "Default",  null, "http")';             
            // Адрес метода печати бегунка
            sourceUrlPrintBegun = '@Url.Action("PrintBegunok", "VedomDoc", new { pBegunCode="param1", pVedCode="param2" }, "http")'; 
            // Адрес для создания бегунков на группу
            sourceUrlCreateBegunForGroup = '@Url.Action("CreateBegunForGroup", "Default", null, "http")'; 


            var mainsplitter = $("#mainSplitter");
            InitSplitter(mainsplitter);

            // Инициализация переменных
            mainTabs = $("#mainTabs");
            splitterContBegun = $("#splitterContBegun");
            // Инициализация переменных
            btnCreateBeguns = $("#btnCreateBeguns");
            btnEditSelBegun = $("#btnEditSelBegun");
            btnPrintSelBegun = $("#btnPrintSelBegun");            

            initInterfaceZadolzh();

            // Отрисовка таблицы со студентами
            studentGrid = $("#studentGrid");
            studentGridInit_Interface();

            // Отрисовка таблицы с бегунками
            begunGrid = $("#begunGrid");
            zadolzhGridInit_Interface();

            var tmpSource = '@Url.Action("GetGroupCollection", null, null, "http")';
            groupGrid = $("#groupGrid");
            sourceUrlGroups = tmpSource.replace('amp;', '');
            InitGroupGrid(groupGrid, sourceUrlGroups);
            
            vedomGrid = $("#vedomGrid");
            InitVedomGrid(vedomGrid);
            
            // Вспомогательные элементы
            labelDepartment = $("#labelDepartment");
            labelGroupName = $("#labelGroupName");
            labelOKCO = $("#labelOKCO");
            labelFO = $("#labelFO");
            labelKurs = $("#labelKurs");
            labelPlanName = $("#labelPlanName");
            ///////////////////////////////
            labelDiscipl = $("#labelDiscipl");
            labelKursVedom = $("#labelKursVedom");
            labelSemVedom = $("#labelSemVedom");
            labelTypeVedom = $("#labelTypeVedom");
            labelSess = $("#labelSess");
            labelSemCalc = $("#labelSemCalc");
            labelVedomNo = $("#labelVedomNo");
            /////////////////////////////////////////////////
            btnNewVedom = $("#btnNewVedom");
            btnNewVedom.jqxButton({ width: '150', height: '25' });
            
            lnkPrintBlank = $("#lnkPrintBlank");
            lnkPrintBlank.jqxLinkButton({ width: '80', height: '25' });
            
            lnkPrintEmpty = $("#lnkPrintEmpty");
            lnkPrintEmpty.jqxLinkButton({ width: '150', height: '25' });
            
            lnkEditVedom = $("#lnkEditVedom");
            lnkEditVedom.jqxLinkButton({ width: '80', height: '25' });
            
            InitVedomButtonsControl();
            
            dlgEditSelBegun = $("#dlgEditSelBegun");
            InitDlgEditSelBegun();
            
            $("#dlgWait").jqxWindow({
                height: 30,
                width: 250,
                resizable: false,
                isModal: true,
                autoOpen: false
            });

        });
    </script>

}

<div>

    @* Элементы управления сверху *@
    <div>
        Пользователь: @ViewBag.AuthMessage
        <br/>
    </div>
    
    @* Окно редактирования бегунка *@
    <div id="dlgEditSelBegun">
        <div id="dlgEditSelBegunCaption">Редактирование бегунка</div>
        <div>
            Оценка: <div id="dlgEditSelBegunOcenka"></div>
            <div style="padding-top: 30px; align-items: center">
                <input type="button" id="okSelBegun" value="Сохранить"/>
                <input type="button" id="cancelSelBegun" value="Отмена"/>
            </div>
        </div>
    </div>
    
     @* Окно ожидания *@
    <div id="dlgWait">
        <div id="dlgWaitCaption">Создание бегунков на группу</div>
        <div id="dlgWaitCaption">...</div>
    </div>

    @* Основное отображение данных *@
    <div class="heightAttestacia">
        <div id="mainSplitter">
            <div>
                @* элементы управления группами *@
                <div>
                    
                </div>
                @* таблица с группами *@
                <div id="groupGrid"></div>
            </div>
            <div>
                @* элементы управления ведомостям *@
                <div>
                    <div style="border-style: solid; border-width: 2px; border-color: gainsboro">
                        <span>Подраз.: <b><label id="labelDepartment">-</label></b></span>
                        <span>Гр.: <b><label id="labelGroupName">-</label></b></span>
                        <span>Спец.: <b><label id="labelOKCO">-</label></b></span>
                        <span>ФО: <b><label id="labelFO">-</label></b></span>
                        <span>Курс: <b><label id="labelKurs">-</label></b></span>
                        <span>План: <b><label id="labelPlanName">-</label></b></span>
                    </div>
                    @* Вкладки *@

                    <div id="mainTabs">
                        <ul>
                            <li>Ведомости</li>
                            <li>Бегунки</li>
                        </ul>
                        @* Вкладка для работы с ведомостями *@
                        <div>
                            @* Информация о ведомостях *@
                            <div style="border-style: solid; border-width: 2px; border-color: gainsboro">
                                <span>Дисцилина: <b><label id="labelDiscipl">-</label></b></span><br/>
                                <span>Курс: <b><label id="labelKursVedom">-</label></b></span> 
                                <label id="labelSemVedom" style="visibility:hidden"></label> 
                                <span>Семестр: <b><label id="labelSemCalc">-</label></b></span>
                                <span>Тип: <b><label id="labelTypeVedom">-</label></b></span> 
                                <label id="labelSess" style="visibility:hidden">-</label>
                                <span>Вед.№: <b><label id="labelVedomNo">-</label></b></span>                     
                            </div>
                            @* Кнопки для ведомостей *@
                            <div style="border-style: solid; border-width: 2px; border-color: gainsboro">
                                <input type="button" value="Новая ведомость" id="btnNewVedom"/>
                                <a target="_blank" href="" id='lnkEditVedom'>Правка</a>
                                <a target="_blank" href="" id='lnkPrintBlank'>Бланк</a>
                                <input type="button" value="Export" id="btnExport" style ="visibility:hidden"/>
                                <a target="_blank" href="" id='lnkPrintEmpty' style="visibility:hidden">Печать (факт)</a>
                            </div>

                            @* таблица с ведомостями *@
                            <div id="vedomGrid"></div>

                        </div>
                        @* Вкладка для работы с бегунками *@
                        <div>
                            @* Управление бегунками *@
                            <div>
                                <input type="button" id="btnCreateBeguns" value="Создать" title="Создать бегунки для всей группы"/> 
                                <input type="button" id="btnEditSelBegun" value="Правка" title="Внести оценку в бегунок"/> 
                                <input type="button" id="btnPrintSelBegun" value="Печать" title="Вывести бегунок на печать"/>                                 
                            </div>
                            @* Splitter: Контингент/бегунки *@
                            <div id="splitterContBegun">
                                @* Контингент *@
                                <div>
                                    @* Таблица студентов *@
                                    <div id="studentGrid"></div>
                                </div>
                                @* Бегунки *@
                                <div>
                                    @* Таблица бегунков *@
                                    <div>
                                        <span>Код: <b><label id="curStudId">-</label></b></span>
                                        <span>ФИО: <b><label id="curStudFIO">-</label></b></span>
                                        <span>Статус: <b><label id="curStudStatus">-</label></b></span>
                                        <span>Состояние задолж.: <b><label id="curIsStudZadolzh">-</label></b></span>
                                    </div>
                                    <div id="begunGrid"></div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>                
            </div>
        </div>       
    </div>
  
    @* Вывод сообщений пользователю *@
    <div></div>

    @* Элементы управления внизу *@
    <div></div>
</div>

Decanat/Views/Default/Vedomost.cshtml
@{
    ViewBag.Title = "Ведомость";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts
{
    <script src="~/Scripts/Custom/Vedom.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            var mainsplitter = $("#mainSplitter");
            InitSplitter(mainsplitter);

            var vedomGrid = $("#vedomGrid");
            InitVedomGrid(vedomGrid);

            var begunGrid = $("#begunGrid");
            InitBegunGrid(begunGrid);

        });
    </script>

}

<div>
    @* Элементы управления сверху *@
    <div>
        Пользователь: @ViewBag.AuthMessage
        <br/>
        @*@Html.ActionLink("Ведомость","Vedomost");*@
    </div>
    
    @* Основное отображение данных *@
    <div class="heightVedom">
        <div id="mainSplitter">
            <div>
                <div id="vedomGrid"></div>
            </div>
            <div>
                <div id="begunGrid"></div>
            </div>
        </div>       
    </div>
  
    @* Вывод сообщений пользователю *@
    <div></div>

    @* Элементы управления внизу *@
    <div></div>
</div>